### ISSUE TITLE
Updates to PyCBC Inference before workshop

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#2617]
The following are things I'd like to have completed before the PyCBC Inference workshop that will take place in May. In no particular order:

- [ ] Merge CPNest on to master (PR #2487 ) (@sum33it )
- [ ] Merge Multinest on to master (PR #2496 ) (@dfinstad )
- [ ] Finish the ROQ model (@Cyberface )
- [ ] Finish the relative binning model (Pr #2536) (@ahnitz )
- [ ] Add the ability to provide an injection file to the injection workflow (PR #2589 ) (@micamu , @JulianWesterweck , @cdcapano )
- [ ] Update the documentation for the standard workflow (?)
- [ ] Make diagnostic plots optional so workflows will work with nested samplers (Issue #2616) (@cmbiwer?)
- [ ] Add support for epsie (@cdcapano )
- [ ] Add custom jump proposal support for epsie (@cdcapano)
- [ ] Add virtual fields for plotting (@micamu?)
- [ ] Remove automatic transforms; replace with explicit waveform transforms (Issue #2407) (?)
- [ ] Rename `waveform_transforms` to something clearer (maybe `model_conversions`?) (?)
- [ ] Add back ability to set different low frequency cutoffs for different detectors (@soumide1102 )
- [ ] Add executable to make the "goose neck plot" (@stevereyes01 ?)
- [ ] `plot_samples` should be able to plot an average chain (by default) (@soumide1102 ?)
- [ ] Posterior files should include metadata (@ahnitz ?)
- [ ] Decide if we want the output files to be posterior files, separate from the checkpoint files (PR #2478); if not, add an `extract_samples` job to the workflows (@ahnitz , @cdcapano , @duncan-brown )
- [ ] Add documentation for running with MPI and in Slurm (@Cyberface ?)

**Comment by micamu** [comment]
@cdcapano I started a PR #2618 for the "Update the documentation for the standard workflow" point. I have only changed the basics in the ringdown ini file now (variable args, approximant name). I assume you also want me to move the "model", "sampler" and "sampler-burn_in" options to the ini files? and make the full IMR ini file to use precessing, like the docs for the inference_inj_workflow do?
